name: Notify Discord
on: [push, pull_request, release]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: nitecon/discord-action@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
